#!/usr/bin/env bash

OUTPUT_PATH=${ANTHONY_OUTPUT_PATH:-./data}
WIPE_BLOCK_SIZE=${ANTHONY_WIPE_BLOCK_SIZE:-128K}
PERFORMANCE_FILE_SIZE=${ANTHONY_PERFORMANCE_FILE_SIZE:-1G}
PERFORMANCE_SMALL_FILE_SIZE=${ANTHONY_PERFORMANCE_SMALL_FILE_SIZE:-256K}
